"""llm_connections table

Revision ID: 17345c9ace52
Revises: 1fbd919c0e04
Create Date: 2026-06-24 22:41:17.226303

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17345c9ace52'
down_revision: str | None = '1fbd919c0e04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_connections',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider_model', sa.String(length=200), nullable=False),
    sa.Column('api_base', sa.String(length=500), nullable=True),
    sa.Column('api_key_ref', sa.String(length=200), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_connections')
    # ### end Alembic commands ###
