"""trigger last_fired_at for scheduler

Revision ID: 57825f870e54
Revises: 00e42d915fe8
Create Date: 2026-06-25 12:39:54.888296

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57825f870e54"
down_revision: str | None = "00e42d915fe8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("triggers", sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("triggers", "last_fired_at")
    # ### end Alembic commands ###
