"""triggers and roles

Revision ID: 637b054bf6fa
Revises: 7ace07be6f59
Create Date: 2026-06-24 23:16:34.285563

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637b054bf6fa'
down_revision: str | None = '7ace07be6f59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triggers',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('event_source', sa.String(length=200), nullable=True),
    sa.Column('event_filter', sa.JSON(), nullable=False),
    sa.Column('loop_config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triggers')
    op.drop_table('roles')
    # ### end Alembic commands ###
