"""data_sources templates channels

Revision ID: 7ace07be6f59
Revises: 580f95bd1819
Create Date: 2026-06-24 23:12:12.741752

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ace07be6f59'
down_revision: str | None = '580f95bd1819'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('render_template', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('compare_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('mcp_server_id', sa.String(length=36), nullable=True),
    sa.Column('connection_ref', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('routing', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('mcp_server_id', sa.String(length=36), nullable=True),
    sa.Column('connection_ref', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('collection', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_sources')
    op.drop_table('channels')
    op.drop_table('templates')
    # ### end Alembic commands ###
